"""add is_admin to user

Revision ID: 38070892b60b
Revises: 950e9639c436
Create Date: 2026-09-03 22:41:32.373041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38070892b60b'
down_revision: Union[str, Sequence[str], None] = '950e9639c436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default='0' backfills existing rows as non-admin — without it, this
    # NOT NULL column add fails outright against a non-empty user table. New rows
    # still default to False at the ORM level (see models/user.py).
    op.add_column(
        'user',
        sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('0')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
