"""add core temporal fact schema

Revision ID: 3cb46f3bcd67
Revises: 
Create Date: 2026-08-27 02:20:03.937302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cb46f3bcd67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('total_episodes', sa.Integer(), nullable=False),
    sa.Column('mal_id', sa.Integer(), nullable=True),
    sa.Column('anilist_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anime_anilist_id'), 'anime', ['anilist_id'], unique=False)
    op.create_index(op.f('ix_anime_mal_id'), 'anime', ['mal_id'], unique=False)
    op.create_index(op.f('ix_anime_slug'), 'anime', ['slug'], unique=True)
    op.create_table('faction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faction_anime_id'), 'faction', ['anime_id'], unique=False)
    op.create_table('temporal_fact',
    sa.Column('fact_id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('predicate', sa.String(length=255), nullable=False),
    sa.Column('object', sa.String(length=500), nullable=False),
    sa.Column('source_citation', sa.String(length=255), nullable=False),
    sa.Column('first_revealed_at', sa.String(length=20), nullable=False),
    sa.Column('first_hinted_at', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fact_id')
    )
    op.create_index(op.f('ix_temporal_fact_anime_id'), 'temporal_fact', ['anime_id'], unique=False)
    op.create_index(op.f('ix_temporal_fact_first_revealed_at'), 'temporal_fact', ['first_revealed_at'], unique=False)
    op.create_index(op.f('ix_temporal_fact_subject'), 'temporal_fact', ['subject'], unique=False)
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('faction_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faction_id'], ['faction.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_anime_id'), 'character', ['anime_id'], unique=False)
    op.create_index(op.f('ix_character_faction_id'), 'character', ['faction_id'], unique=False)
    op.create_index(op.f('ix_character_name'), 'character', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_name'), table_name='character')
    op.drop_index(op.f('ix_character_faction_id'), table_name='character')
    op.drop_index(op.f('ix_character_anime_id'), table_name='character')
    op.drop_table('character')
    op.drop_index(op.f('ix_temporal_fact_subject'), table_name='temporal_fact')
    op.drop_index(op.f('ix_temporal_fact_first_revealed_at'), table_name='temporal_fact')
    op.drop_index(op.f('ix_temporal_fact_anime_id'), table_name='temporal_fact')
    op.drop_table('temporal_fact')
    op.drop_index(op.f('ix_faction_anime_id'), table_name='faction')
    op.drop_table('faction')
    op.drop_index(op.f('ix_anime_slug'), table_name='anime')
    op.drop_index(op.f('ix_anime_mal_id'), table_name='anime')
    op.drop_index(op.f('ix_anime_anilist_id'), table_name='anime')
    op.drop_table('anime')
    # ### end Alembic commands ###
