"""add anime season episode counts

Revision ID: 5894761126d1
Revises: 3cb46f3bcd67
Create Date: 2026-08-27 02:33:24.447230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5894761126d1'
down_revision: Union[str, Sequence[str], None] = '3cb46f3bcd67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'anime',
        sa.Column('season_episode_counts', sa.JSON(), nullable=False, server_default='[]'),
    )
    with op.batch_alter_table('anime') as batch_op:
        batch_op.alter_column('season_episode_counts', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anime', 'season_episode_counts')
    # ### end Alembic commands ###
