"""add email verification and password reset to user

Revision ID: 950e9639c436
Revises: bec1a3e2222d
Create Date: 2026-09-03 17:16:52.286909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '950e9639c436'
down_revision: Union[str, Sequence[str], None] = 'bec1a3e2222d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default='1' grandfathers existing accounts (created before this
    # migration, so they never went through email verification) as already
    # verified — without it, every pre-existing user would be locked out of login
    # by the new is_verified gate. New rows still default to False at the ORM
    # level (see models/user.py); the server_default only backfills old ones.
    op.add_column(
        'user',
        sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.text('1')),
    )
    op.add_column('user', sa.Column('verification_token', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('verification_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user', sa.Column('reset_password_token', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('reset_password_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_user_reset_password_token'), 'user', ['reset_password_token'], unique=False)
    op.create_index(op.f('ix_user_verification_token'), 'user', ['verification_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_verification_token'), table_name='user')
    op.drop_index(op.f('ix_user_reset_password_token'), table_name='user')
    op.drop_column('user', 'reset_password_token_expires_at')
    op.drop_column('user', 'reset_password_token')
    op.drop_column('user', 'verification_token_expires_at')
    op.drop_column('user', 'verification_token')
    op.drop_column('user', 'is_verified')
    # ### end Alembic commands ###
