"""add fact source tagging and external metadata

Revision ID: cb93834dfeed
Revises: 5894761126d1
Create Date: 2026-08-27 03:08:21.332600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb93834dfeed'
down_revision: Union[str, Sequence[str], None] = '5894761126d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime_external_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('episodes', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anime_external_metadata_anime_id'), 'anime_external_metadata', ['anime_id'], unique=False)
    op.create_index(op.f('ix_anime_external_metadata_source'), 'anime_external_metadata', ['source'], unique=False)
    op.add_column(
        'temporal_fact',
        sa.Column('source', sa.String(length=20), nullable=False, server_default='curated'),
    )
    with op.batch_alter_table('temporal_fact') as batch_op:
        batch_op.alter_column('source', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temporal_fact', 'source')
    op.drop_index(op.f('ix_anime_external_metadata_source'), table_name='anime_external_metadata')
    op.drop_index(op.f('ix_anime_external_metadata_anime_id'), table_name='anime_external_metadata')
    op.drop_table('anime_external_metadata')
    # ### end Alembic commands ###
